refactor: Recursively look for the project root
pdm-project/pdm pull request #2286
Opened 2023-09-28 20:18 UTC by xulongwu4

## Pull Request Checklist

- [ ] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

## Describe what you have changed in this PR.

This PR refactors the `find_project_root()` and `find_pypackage()` functions so that they now recursively looks for the `pyproject.toml` file or the `__pypackages__/{version}/lib` directory in the current directory or its parent directory. This means that we no longer need to set an upper limit on the number of levels we tranverse in such a search, and the `PDM_PROJECT_MAX_DEPTH` environment variable and the `project_max_depth` setting is no longer useful.

2023-09-29 02:48 UTC, frostming approved these changes

2023-09-29 02:53 UTC, frostming requested changes
Can you add a news fragment under `news/`?

2023-09-29 03:03 UTC, xulongwu4 commented
Added a news fragment

2023-10-06 00:59 UTC, merged

2023-10-08 08:53 UTC, drunkwcodes commented
Well done, @xulongwu4 !
mojo-muse also appreciate your work.