Update `run` to support `pyenv` shims on macOS
pdm-project/pdm pull request #535
Opened 2021-07-10 02:58 UTC by jeffreyc

## Pull Request Check List

- [x] A news fragment is added in `news/` describing what is new.
- [ ] Test cases added for changed code.

## Describe what you have changed in this PR.

This is an attempt to fix #494, where PDM fails with "OSError: [Errno 8] Exec format error" when using pyenv shims on macOS. This error appears to be specific to macOS; I was unable to recreate it in a Linux Docker image.

Per https://stackoverflow.com/a/49131318, I believe this error happens when the shebang points to a text file instead of a binary. Manual testing confirms this error happens when the shebang points to `~/.pyenv/shims/python` and not when the shebang points to `~/.pyenv/versions/3.9.6/bin/python3.9` (the executable instead of the shim) or when invoked by passing the Python executable/shim as the first argument to `execv`.

Passing `project.python_executable` seems more straightforward than rewriting the shebang, since it's non-trivial to detect the shim's target, but feel free to suggest another approach.

I spent a little time looking at testing this only to realize it's not really testable, since the modified code is in a code path that's intentionally not executed when running tests. I did try modifying https://github.com/pdm-project/pdm/blob/main/pdm/cli/commands/run.py#L94 but it breaks a bunch of existing tests without adding clear value because it's not testing the modified code. Besides, this code is exercised when running `pdm run test`, so if it doesn't work, the test suite will fail.

Fixes #494.

2021-07-10 03:54 UTC, frostming requested changes
Must test if the command is a python script.

2021-07-10 04:50 UTC, jeffreyc commented
> Must test if the command is a python script.

Is there a risk `python_executable` won't be a valid Python interpreter? The code around setting that appears pretty robust. I added a check, but it's not clear the `else` branch is reachable. If I misunderstood and there's another concern, please let me know.

2021-07-10 08:44 UTC, frostming commented
You might get me wrong, i mean the first arg following python_executable must be a valid Python script. Just think of `pdm run ls -l`. One possible way is to look at the shebang line or if there's any better approach.

2021-07-10 15:12 UTC, jeffreyc commented
Apologies, I misunderstood and didn't realize `pdm run ls -l` was a valid use case. I'll close this for now,

2021-07-10 15:12 UTC, closed without merging

2021-07-11 00:00 UTC, frostming commented
It's OK, is it valid for pyenv shims Python as the shebang line? If not, we should avoid this in the first place.

2021-07-11 01:39 UTC, jeffreyc commented
> is it valid for pyenv shims Python as the shebang line? If not, we should avoid this in the first place.

It depends. I think using a script as the interpreter is only supported on Linux/Minix, _but_ it also appears to be supported by zsh on macOS. So a script in the local package directory using shims should work when called directly if your shell is zsh (the current default shell on macOS), but not when invoked via `os.execv` et al, which I believe use `/bin/sh`